POST http://localhost:8080/api/wards
Content-Type: application/json

{
  "name": "surgical",
  "numberOfBeds": 2,
  "areaInSquareMeters": 100.0
}

###
GET http://localhost:8080/api/wards/1

Accept: application/json

###
GET http://localhost:8080/api/wards
Accept: application/json

###
GET http://localhost:8080/api/patients/11111

Accept: application/json

###
GET http://localhost:8080/api/patients
Accept: application/json

###
POST http://localhost:8080/api/patients
Content-Type: application/json

{"pesel": "53542",
  "firstName": "Borys",
  "lastName": "Drwalski",
  "age": 33,
  "ward": "3"
}

###
GET http://localhost:8080/api/wards/1/patients

Accept: application/json

###

POST http://localhost:8080/api/wards/1/patients

Content-Type: application/json

{"pesel": "11111",
  "firstName": "Andrzej",
  "lastName": "Litewski",
  "age": 11,
  "ward": "12"
}

###
DELETE localhost:8080/api/wards/1/patients/11111
###

PUT localhost:8080/api/wards/1
Content-Type: application/json

{
  "name": "maternity2",
  "numberOfBeds": 100,
  "areaInSquareMeters": 300
}

###
DELETE localhost:8080/api/patients/0123

###
DELETE localhost:8080/api/wards/1

###
GET localhost:8080/api/wards/2/patients

###
DELETE localhost:8080/api/wards/2/patients/4567


