GET http://localhost:8082/api/patients
Accept: application/json

###
POST http://localhost:8082/api/patients
Content-Type: application/json

{"pesel": "53542",
  "firstName": "Borys",
  "lastName": "Drwalski",
  "age": 33,
  "ward": "causality"
}

###
GET http://localhost:8082/api/patients/53542
Accept: application/json

###


GET http://localhost:8082/api/wards/surgical/patients
Accept: application/json

###

POST http://localhost:8082/api/wards/maternity/patients
Content-Type: application/json

{"pesel": "11111",
  "firstName": "Andrzej",
  "lastName": "Litewski",
  "age": 11,
  "ward": "mater"
}

###
DELETE localhost:8082/api/wards/maternity/patients/11111

###
DELETE localhost:8082/api/patients/0123

###
GET localhost:8082/api/wards/maternity230/patients

###
DELETE localhost:8082/api/wards/general/patients/4567

###

DELETE localhost:8082/api/wards/general

###

POST localhost:8082/api/wards
Content-Type: application/json

{
  "name": "maternity230"
}


